export const EC_FEATURES = Object.freeze([
  {
    version: 2.12,
    feature: true,
    title: "Switch to ESLint",
    link: "https://blog.emberjs.com/2017/03/19/ember-2-12-released.html",
  },
  {
    version: 2.13,
    feature: true,
    title: "Add support for using yarn",
    link: "https://blog.emberjs.com/2017/04/29/ember-2-13-released.html",
  },
  {
    version: 2.13,
    feature: true,
    title: "Enable Instrumentation Hooks",
    link: "https://blog.emberjs.com/2017/04/29/ember-2-13-released.html",
  },
  {
    version: 2.13,
    feature: true,
    title: "Targets",
    link: "https://blog.emberjs.com/2017/04/29/ember-2-13-released.html",
  },
  {
    version: 2.13,
    feature: true,
    title: "Babel 6",
    link: "https://blog.emberjs.com/2017/04/29/ember-2-13-released.html",
  },
  {
    version: 2.14,
    feature: true,
    title: "Specifying a blueprint for a new app",
    link: "https://blog.emberjs.com/2017/07/06/ember-2-14-released.html",
  },
  {
    version: 2.14,
    feature: true,
    title: "NPM 5 and Node 8 support",
    link: "https://blog.emberjs.com/2017/07/06/ember-2-14-released.html",
  },
  {
    version: 2.15,
    feature: true,
    title: "Other Notable Changes",
    link: "https://blog.emberjs.com/2017/09/01/ember-2-15-released.html",
  },
  {
    version: 2.15,
    feature: true,
    title: "Improved Error Messages",
    link: "https://blog.emberjs.com/2017/09/01/ember-2-15-released.html",
  },
  {
    version: 2.15,
    feature: true,
    title: "Chrome by default",
    link: "https://blog.emberjs.com/2017/09/01/ember-2-15-released.html",
  },
  {
    version: 2.15,
    feature: true,
    title: "Node.js 8 Support",
    link: "https://blog.emberjs.com/2017/09/01/ember-2-15-released.html",
  },
  {
    version: 2.15,
    feature: true,
    title: "app.import files within node_modules",
    link: "https://blog.emberjs.com/2017/09/01/ember-2-15-released.html",
  },
  {
    version: 2.16,
    feature: true,
    title: "Project configuration is cached as a performance optimization",
    link: "https://blog.emberjs.com/2017/10/11/ember-2-16-released.html",
  },
  {
    version: 2.16,
    feature: true,
    title: "Addon API for Custom Transforms",
    link: "https://blog.emberjs.com/2017/10/11/ember-2-16-released.html",
  },
  {
    version: 2.16,
    feature: true,
    title: "ember install supports scoped npm packages",
    link: "https://blog.emberjs.com/2017/10/11/ember-2-16-released.html",
  },
  {
    version: 2.16,
    feature: true,
    title: "Support for the Ember CLI strategies RFC",
    link: "https://blog.emberjs.com/2017/10/11/ember-2-16-released.html",
  },
  {
    version: 2.17,
    feature: true,
    title: "ember test --server",
    link: "https://blog.emberjs.com/2017/11/20/ember-2-17-released.html",
  },
  {
    version: 3.02,
    feature: true,
    title: "qunit-dom",
    link: "https://blog.emberjs.com/2018/07/02/ember-3-2-released.html",
  },
  {
    version: 3.02,
    feature: true,
    title: "Update ember-cli-qunit dependency",
    link: "https://blog.emberjs.com/2018/07/02/ember-3-2-released.html",
  },
  {
    version: 3.04,
    feature: true,
    title: "Added Support for Node 10",
    link: "https://blog.emberjs.com/2018/10/07/ember-3-4-released.html",
  },
  {
    version: 3.04,
    feature: true,
    title: "Template Linting",
    link: "https://blog.emberjs.com/2018/10/07/ember-3-4-released.html",
  },
  {
    version: 3.05,
    feature: true,
    title: "Upgraded to Broccoli v2.0.0!",
    link: "https://blog.emberjs.com/2018/10/15/ember-3-5-released.html",
  },
  {
    version: 3.05,
    feature: true,
    title: "Build speed improvements up to 32%",
    link: "https://blog.emberjs.com/2018/10/15/ember-3-5-released.html",
  },
  {
    version: 3.05,
    feature: true,
    title: "Migration to ember-qunit",
    link: "https://blog.emberjs.com/2018/10/15/ember-3-5-released.html",
  },
  {
    version: 3.06,
    feature: true,
    title: "Prevent double builds in CI",
    link: "https://blog.emberjs.com/2018/12/13/ember-3-6-released.html",
  },
  {
    version: 3.07,
    feature: true,
    title: "Compatibility section in addon README",
    link: "https://blog.emberjs.com/2019/01/07/ember-3-7.html",
  },
  {
    version: 3.07,
    feature: true,
    title: "Remove last usage of Babel 6",
    link: "https://blog.emberjs.com/2019/01/07/ember-3-7.html",
  },
  {
    version: 3.09,
    feature: true,
    title: "ember-welcome-page updated to use angle bracket invocation syntax",
    link: "https://blog.emberjs.com/2019/04/10/ember-3-9-released.html",
  },
  {
    version: 3.09,
    feature: true,
    title: "Support for Node 11",
    link: "https://blog.emberjs.com/2019/04/10/ember-3-9-released.html",
  },
  {
    version: 3.1,
    feature: true,
    title: "Native Decorator Support",
    link: "https://blog.emberjs.com/2019/05/21/ember-3-10-released.html",
  },
  {
    version: 3.1,
    feature: true,
    title: "Drop Node 6 support",
    link: "https://blog.emberjs.com/2019/05/21/ember-3-10-released.html",
  },
  {
    version: 3.16,
    feature: true,
    title: "Drop Node 8 support",
    link: "https://blog.emberjs.com/2020/02/12/ember-3-16-released.html",
  },
  {
    version: 3.16,
    feature: true,
    title: "Drop Ember 3.8 from ember-try test scenarios in addon blueprints",
    link: "https://blog.emberjs.com/2020/02/12/ember-3-16-released.html",
  },
]);
export const EC_DEPRECATIONS = Object.freeze([
  {
    version: 2.13,
    deprecation: true,
    title: "bower.json",
    link: "https://blog.emberjs.com/2017/04/29/ember-2-13-released.html",
  },
  {
    version: 2.15,
    deprecation: true,
    title: "PhantomJS no longer actively maintained",
    link: "https://blog.emberjs.com/2017/09/01/ember-2-15-released.html",
  },
  {
    version: 3.02,
    deprecation: true,
    title: "ember-cli-babel 5",
    link: "https://blog.emberjs.com/2018/07/02/ember-3-2-released.html",
  },
  {
    version: 3.14,
    deprecation: true,
    title: "MODULE_UNIFICATION flag",
    link: "https://blog.emberjs.com/2019/11/18/ember-3-14-released.html",
  },
]);
