export const ED_FEATURES = Object.freeze([
  {
    version: 2.04,
    feature: true,
    title: "Friendly Errors",
    link: "https://blog.emberjs.com/2016/03/13/ember-data-2-4-released.html",
  },
  {
    version: 2.04,
    feature: true,
    title: "Importing Modules",
    link: "https://blog.emberjs.com/2016/03/13/ember-data-2-4-released.html",
  },
  {
    version: 2.04,
    feature: true,
    title: "Fastboot Support",
    link: "https://blog.emberjs.com/2016/03/13/ember-data-2-4-released.html",
  },
  {
    version: 2.05,
    feature: true,
    title: "ds-finder-include",
    link: "https://blog.emberjs.com/2016/05/03/ember-data-2-5-released.html",
  },
  {
    version: 2.05,
    feature: true,
    title: "ds-references",
    link: "https://blog.emberjs.com/2016/05/03/ember-data-2-5-released.html",
  },
  {
    version: 2.05,
    feature: true,
    title: "ds-transform-pass-options",
    link: "https://blog.emberjs.com/2016/05/03/ember-data-2-5-released.html",
  },
  {
    version: 2.06,
    feature: true,
    title: "ds-serialize-ids-and-types",
    link: "https://blog.emberjs.com/2016/05/03/ember-data-2-5-released.html",
  },
  {
    version: 2.07,
    feature: true,
    title: "ds-boolean-transform-allow-null",
    link: "https://blog.emberjs.com/2016/07/25/ember-data-2-7-released.html",
  },
  {
    version: 2.07,
    feature: true,
    title: "ds-links-in-record-array",
    link: "https://blog.emberjs.com/2016/07/25/ember-data-2-7-released.html",
  },
  {
    version: 2.08,
    feature: true,
    title: "ds-improved-ajax",
    link: "https://blog.emberjs.com/2016/07/25/ember-data-2-7-released.html",
  },
  {
    version: 2.11,
    feature: true,
    title: "HasMany Computed Property Keys",
    link: "https://blog.emberjs.com/2017/01/23/ember-2-11-released.html",
  },
  {
    version: 2.12,
    feature: true,
    title: "A new serializeId() method",
    link: "https://blog.emberjs.com/2017/03/19/ember-2-12-released.html",
  },
  {
    version: 2.13,
    feature: true,
    title: "ds-extended-errors (#3586 #4287)",
    link: "https://blog.emberjs.com/2017/04/29/ember-2-13-released.html",
  },
  {
    version: 2.14,
    feature: true,
    title: "Deferred serializer lookup",
    link: "https://blog.emberjs.com/2017/07/06/ember-2-14-released.html",
  },
  {
    version: 2.14,
    feature: true,
    title: "Lazy Relationships",
    link: "https://blog.emberjs.com/2017/07/06/ember-2-14-released.html",
  },
  {
    version: 2.14,
    feature: true,
    title: "File-size Improvements",
    link: "https://blog.emberjs.com/2017/07/06/ember-2-14-released.html",
  },
  {
    version: 3.02,
    feature: true,
    title: "Lazy Relationship Payloads",
    link: "https://blog.emberjs.com/2018/07/02/ember-3-2-released.html",
  },
  {
    version: 3.02,
    feature: true,
    title: "Ember Data Feature Flag Removal",
    link: "https://blog.emberjs.com/2018/07/02/ember-3-2-released.html",
  },
  {
    version: 3.02,
    feature: true,
    title: "Feature Flag ds-improved-ajax",
    link: "https://blog.emberjs.com/2018/07/02/ember-3-2-released.html",
  },
  {
    version: 3.02,
    feature: true,
    title: "Feature Flag ds-pushpayload-return",
    link: "https://blog.emberjs.com/2018/07/02/ember-3-2-released.html",
  },
  {
    version: 3.05,
    feature: true,
    title: "RecordData",
    link: "https://blog.emberjs.com/2018/10/15/ember-3-5-released.html",
  },
  {
    version: 3.09,
    feature: true,
    title: "Replace jQuery with fetch",
    link: "https://blog.emberjs.com/2019/04/10/ember-3-9-released.html",
  },
  {
    version: 3.11,
    feature: true,
    title: "Packages feature",
    link: "https://blog.emberjs.com/2019/07/15/ember-3-11-released.html",
  },
  {
    version: 3.15,
    feature: true,
    title: "Identifiers",
    link: "https://blog.emberjs.com/2019/12/20/ember-3-15-released.html",
  },
  {
    version: 3.15,
    feature: true,
    title: "Inspector Support is now optional in production",
    link: "https://blog.emberjs.com/2019/12/20/ember-3-15-released.html",
  },
]);
export const ED_DEPRECATIONS = Object.freeze([
  {
    version: 2.11,
    deprecation: true,
    title: "store#lookupAdapter() and store#lookupSerializer()",
    link: "https://blog.emberjs.com/2017/01/23/ember-2-11-released.html",
  },
  {
    version: 2.11,
    deprecation: true,
    title: "store#serialize()",
    link: "https://blog.emberjs.com/2017/01/23/ember-2-11-released.html",
  },
  {
    version: 2.11,
    deprecation: true,
    title: "store#recordIsLoaded()",
    link: "https://blog.emberjs.com/2017/01/23/ember-2-11-released.html",
  },
  {
    version: 2.13,
    deprecation: true,
    title: "data-adapter, injectStore, transforms, and store",
    link: "https://blog.emberjs.com/2017/04/29/ember-2-13-released.html",
  },
  {
    version: 2.14,
    deprecation: true,
    title: "didUpdateAll and buildInternalModel",
    link: "https://blog.emberjs.com/2017/07/06/ember-2-14-released.html",
  },
  {
    version: 2.18,
    deprecation: true,
    title: "Support for 'production-like' values of EMBER_ENV",
    link: "https://blog.emberjs.com/2018/01/01/ember-2-18-released.html",
  },
  {
    version: 3.01,
    deprecation: true,
    title: "Ember.Map",
    link: "https://blog.emberjs.com/2018/04/13/ember-3-1-released.html",
  },
  {
    version: 3.12,
    deprecation: true,
    title: "Evented Api Usage",
    link: "https://blog.emberjs.com/2019/08/16/ember-3-12-released.html",
  },
  {
    version: 3.12,
    deprecation: true,
    title: "Record Lifecycle Event Methods",
    link: "https://blog.emberjs.com/2019/08/16/ember-3-12-released.html",
  },
  {
    version: 3.14,
    deprecation: true,
    title: "Default Adapters and Serializers",
    link: "https://blog.emberjs.com/2019/11/18/ember-3-14-released.html",
  },
]);
